package net.c0nan.dao.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * @author Jannie Pieterse
 * - useage explanation inside net.c0nan.doc.NotJPADoc
 * - Use this annotation to tag a field as an DBDTO key field, thus it will be managed by Binder
 * - Name - Just a name
 * - Auto generated - this avoids the field from being included in the insert statement, and the expects it back from 
 *   the insert statement
 * 
 */

@Retention(RetentionPolicy.RUNTIME)
public @interface DBKey {
	public String Name() default "";
	public boolean AutoGenerated() default false;
}
